### ISSUE TITLE
BroadWorks AS1 not sending XSLog files

### ISSUE THREAD

**Issue by kporter5302** [BroadSoft-Xtended/BroadWorks-Dashboards-and-Discovery#110]
Recently our AS1 Server stopped sending XSLog files to the Kibana Server.  It is however still sending PSLogs, SWManagerActivities logs and ConfigAgent logs.  Can anyone help me get the XSLog sending fixed?  I would also like to know how to disable the sending of any log files other than XSLogs?????

**Comment by kporter5302** [comment]
Here's the Exception that the server pops during a restart of the bwlogsender:
Exception in thread "TailRunner => XSLog" java.lang.NullPointerException
        at com.broadsoft.zipsender.FilePersistance.read(FilePersistance.java:150)
        at com.broadsoft.zipsender.TailerRunner.run(TailerRunner.java:152)
        at java.lang.Thread.run(Thread.java:748)
