### ISSUE TITLE
logreceiver won't run - can't find slf4j

### ISSUE THREAD

**Issue by mdasilva-mettel** [BroadSoft-Xtended/BroadWorks-Dashboards-and-Discovery#29]
Using Oracle Java and Elasticsearch both installed from apt-get on Debian 9:

`Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at com.broadsoft.eslogzipreceiver.Main.<clinit>(Main.java:32)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:375)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
        ... 4 more`

**Comment by dstewart-broadsoft** [comment]
slf4j is actually packaged in the generated jar eslogreceiver.jar so kind of weird.

What version of java is installed? And is it openjdk or Oracles? (java -version)

**Comment by mdasilva-mettel** [comment]
Oracle Java 9 is installed:

`$ java -version
java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)`

**Comment by dstewart-broadsoft** [comment]
Reproduced with jdk 9 (only been out a couple weeks - surprised it's already being distributed).
Best thing at the moment is see if you can install jdk 8 - we run CI/Regression with jdk7 and jdk8 and haven't see this.

Dave

**Comment by mdasilva-mettel** [comment]
Uninstalled 9, installed 8. Working now. Thank you.
