### ISSUE TITLE
Authentication issue 

### ISSUE THREAD

**Issue by vphimmasone** [BroadSoft-Xtended/BroadWorks-Dashboards-and-Discovery#30]
Hi,

I installed x-pack and now i can't receive any logs on bwlog - It requests a username password which i have however where does the username/password need to be configured - Below the bwlogreceiver trace 

2017-10-09_20:03:06.534 [NetworkSocketListener] INFO  c.b.eslogzipreceiver.NetworkSocket - Connection established from: /xx.xx.xx.xx:46543
2017-10-09_20:03:06.548 [Incoming connection from: xx.xx.xx.xx] INFO  c.b.eslogzipreceiver.NetworkSocket - run method that is doing nothing
2017-10-09_20:03:13.771 [Timer-0] INFO  c.b.e.ElasticLogIndexer - FlusherTask initiated
2017-10-09_20:03:16.299 [I/O dispatcher 1] INFO  c.b.e.ElasticLogIndexer - onFailure exception
org.elasticsearch.client.ResponseException: POST http://xx.xx.xx.xx\:9200/_bulk: HTTP/1.1 401 Unauthorized
{"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication token for REST request [/_bulk]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}}],"type":"security_exception","reason":"missing authentication token for REST request [/_bulk]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}},"status":401}
        at org.elasticsearch.client.RestClient$1.completed(RestClient.java:311)
        at org.elasticsearch.client.RestClient$1.completed(RestClient.java:300)
        at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
        at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
        at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)

**Comment by vphimmasone** [comment]
Any update - Is there something we can fix ?

**Comment by Zeal0us** [comment]
I believe you're looking for ESAUTHUSER and ESAUTHPASS in logreceiver.props in the bwlogreceiver directory
