### ISSUE TITLE
XSP node - Sender will not start after restart

### ISSUE THREAD

**Issue by kdotson3263k** [BroadSoft-Xtended/BroadWorks-Dashboards-and-Discovery#65]
Server was running fine.  I restarted because I had to delete the apache elasticsearch index.  
I deleted the ".Apache_persistfile.txt" before stopping the logsender service.  I then delete the elasticsearch index, and attempted to restart the logsender.

**bwlogsenderlogs.txt:**
2019-01-18_01:48:33.880 [Thread-2] INFO  c.b.zipsender.ShutdownHandler - Caught shutdown.... Stopping processors. This will take up to 5000 milliseconds
2019-01-18_01:48:33.953 [TailRunner => access_log] INFO  com.broadsoft.zipsender.TailerRunner - Shutting down processor for Apache
2019-01-18_01:48:33.953 [TailRunner => access_log] INFO  com.broadsoft.zipsender.TailerRunner - Persisted access_log.2019-01-18-00_56_46 at log number 37377
2019-01-18_01:48:34.182 [TailRunner => dmsDebugLog] INFO  com.broadsoft.zipsender.TailerRunner - Shutting down processor for dmsDebug
2019-01-18_01:48:34.182 [TailRunner => dmsDebugLog] INFO  com.broadsoft.zipsender.TailerRunner - Persisted dmsDebugLog2019.01.18-01.34.47.txt at log number 68114
2019-01-18_01:48:34.255 [TailRunner => snmp] INFO  com.broadsoft.zipsender.TailerRunner - Shutting down processor for SNMP
2019-01-18_01:48:34.255 [TailRunner => snmp] INFO  com.broadsoft.zipsender.TailerRunner - Persisted snmpplatformpmd09.log at log number 0
2019-01-18_01:48:34.734 [TailRunner => XsiActions] INFO  com.broadsoft.zipsender.TailerRunner - Shutting down processor for XsiActions
2019-01-18_01:48:34.734 [TailRunner => XsiActions] INFO  com.broadsoft.zipsender.TailerRunner - Persisted XsiActionsLog2019.01.18-01.30.27.txt at log number 11086
2019-01-18_01:48:35.040 [TailRunner => swmanagerActivities] INFO  com.broadsoft.zipsender.TailerRunner - Shutting down processor for SWManager
2019-01-18_01:48:35.040 [TailRunner => swmanagerActivities] INFO  com.broadsoft.zipsender.TailerRunner - Persisted swmanagerActivities_2019.01.14-14.50.02.txt at log number 57607
2019-01-18_01:48:35.489 [TailRunner => lmLog] INFO  com.broadsoft.zipsender.TailerRunner - Shutting down processor for LicenseManager
2019-01-18_01:48:35.489 [TailRunner => lmLog] INFO  com.broadsoft.zipsender.TailerRunner - Persisted lmLog2019.01.11-18.00.02.txt at log number 985
2019-01-18_01:48:35.771 [TailRunner => configd2] INFO  com.broadsoft.zipsender.TailerRunner - Shutting down processor for ConfigAgent
2019-01-18_01:48:35.771 [TailRunner => configd2] INFO  com.broadsoft.zipsender.TailerRunner - Persisted configd2018.10.09-23.05.08.txt at log number 98950
2019-01-18_01:48:35.785 [TailRunner => XsiEvents] INFO  com.broadsoft.zipsender.TailerRunner - Shutting down processor for XsiEvents
2019-01-18_01:48:35.785 [TailRunner => XsiEvents] INFO  com.broadsoft.zipsender.TailerRunner - Persisted XsiEventsLog2019.01.17-23.53.23.txt at log number 31549
2019-01-18_01:48:38.883 [Thread-2] INFO  c.b.zipsender.ShutdownHandler - Shutdown complete.... Application is shutting down

**[root@wdv-xsp01 monitoring]# cat bwlogsendererr.txt**
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at com.broadsoft.zipsender.Main.<clinit>(Main.java:35)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:266)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
        ... 4 more
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at com.broadsoft.zipsender.Main.<clinit>(Main.java:35)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:266)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
        ... 4 more

[root@wdv-xsp01 monitoring]# java -version
java version "1.7.0_21"
Java(TM) SE Runtime Environment (build 1.7.0_21-b11)
Java HotSpot(TM) 64-Bit Server VM (build 23.21-b01, mixed mode)

**Comment by kdotson3263k** [comment]
I completely removed and reinstalled 'bwlogsender_1021.run" with the same results.

**Comment by kdotson3263k** [comment]
[root@wdv-xsp01 nagios]# grep -v "#" /usr/local/bwlogsender/bwlogsender/logsender.props
enabled:true
servertype:XSP
receiverserver:XXXX
receiverport:9072
senderreceiverusessl:true
kafkaserver:None
kafkaport:9092
topicname:bwlog
topicgroup:sendgroup
usekafka:false
senderlogqueuesize:1000
numbersenderwritethreads:1
zipblocksize:128000
jvmheapsize:512m
processmonitormaxthreads:100
processmonitormaxfiles:100
logsenderdebugging:false

**Comment by kdotson3263k** [comment]
FYI,
I was able to get the sender working via the "bwlogsender.pl --start" script, but I cannot with the "service bwlogsender start"  I am assuming I have some sort of permissions or environment issue.

**Comment by gokulbsft** [comment]
If you still see the error,
"Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory", please verify that the jar file slf4j-api-1.7.18.jar or slf4j-api-1.7.25.jar present inside the jar "eslogsender.jar".

**Comment by kdotson3263k** [comment]
Both are there:

[root@wdv-xsp01 bwlogsender]# jar -tf eslogsender.jar | grep slf4j-api-1.7.18.jar
slf4j-api-1.7.18.jar
[root@wdv-xsp01 bwlogsender]# jar -tf eslogsender.jar | grep slf4j-api-1.7.25.jar
slf4j-api-1.7.25.jar
