### ISSUE TITLE
Logsender Error

### ISSUE THREAD

**Issue by kdotson3263k** [BroadSoft-Xtended/BroadWorks-Dashboards-and-Discovery#67]
See this in the logs after updating "XSP_channel.props" with non-standard log file name and location for the CommPilot and restarting service:

2019-02-19_19:58:03.096 [Thread-29] INFO  com.broadsoft.zipsender.TailerRunner - Tailrunner for file: null generated an exception
2019-02-19_19:58:03.097 [TailRunner => WSLog] INFO  com.broadsoft.zipsender.TailerRunner - File => WSLog2019.02.19-19.53.49.txt processed <2771> logs and processed <132215> lines.
2019-02-19_19:58:03.097 [TailRunner => WSLog] INFO  com.broadsoft.zipsender.TailerRunner - Starting file => WSLog2019.02.19-19.54.14.txt
2019-02-19_19:58:03.098 [TailRunner => WSLog] INFO  com.broadsoft.zipsender.TailerRunner - Creating new Tailer for WSLog2019.02.19-19.54.14.txt
2019-02-19_19:58:03.100 [Thread-29] INFO  com.broadsoft.zipsender.TailerRunner - Exception from Tailer thread. Needs investigation.
java.lang.NullPointerException: null
        at com.broadsoft.zipsender.LogParserBase.delivers(LogParserBase.java:173)
        at com.broadsoft.zipsender.LogParserBase.deliver(LogParserBase.java:112)
        at com.broadsoft.zipsender.TailerRunner$LogTailerListener.handle(TailerRunner.java:543)
        at com.broadsoft.zipsender.Tailer.readLines(Tailer.java:619)
        at com.broadsoft.zipsender.Tailer.run(Tailer.java:526)
        at java.lang.Thread.run(Thread.java:722)

**[root@wdv-ews09 bwlogsender]# cat XSP_channel.props**
channelfile:XsiActions:/var/broadworks/logs/xsp:XsiActions:*:dailyallserver
channelfile:XsiEvents:/var/broadworks/logs/xsp:XsiEvents:*:dailyallserver
channelfile:dmsDebug:/var/broadworks/logs/xsp:dmsDebugLog:*:dailyallserver
channelfile:NPS:/var/broadworks/logs/xsp:NPS:*:dailyallserver
channelfile:OciOverSoap:/var/broadworks/logs/xsp:OciOverSoapLog:*:dailyallserver
channelfile:CommPilot:/var/broadworks/logs/webserver:WSLog:*:dailyallserver
channelfile:OCIFiles:/var/broadworks/logs/xsp:OCIFilesLog:*:dailyallserver
channelfile:Apache:/var/broadworks/logs/apache:access_log:*:dailyallserver
channelfile:UserLocation:/var/broadworks/logs/xsp:UserLocation:*:dailyallserver
channelfile:SIPLocation:/var/broadworks/logs/siplocation:SIPLocation:*:dailyallserver

# Platform Channels
channelfile:SWManager:/var/broadworks/logs/swmanager:swmanagerActivities:*:dailyallserver
channelfile:ConfigAgent:/var/broadworks/logs/config:configd2:*:dailyallserver
channelfile:LicenseManager:/var/broadworks/logs/lmd:lmLog:*:dailyallserver
channelfile:SNMP:/var/broadworks/logs/snmp:snmp:*:dailyallserver

**Comment by kdotson3263k** [comment]
I am not seeing anything but the CommPilot logs in Elasticsearch.

**Comment by kdotson3263k** [comment]
I put back the old config and it appears that the apache logs are still not indexing even though both log sender and receiver are working properly.

Any suggestions on how to troubleshoot?

**Comment by kdotson3263k** [comment]
Closing, looks like my elasticsearch index was corrupted.
