### ISSUE TITLE
bwlogreceiver - error

### ISSUE THREAD

**Issue by kdotson3263k** [BroadSoft-Xtended/BroadWorks-Dashboards-and-Discovery#86]
I am seeing this in the logging every once in a while.  I assume this is due to elasticsearch being too busy, but wonder if there are any settings I can work with to help alleviate the pressure?

2019-09-13_14:19:29.827 [I/O dispatcher 10] INFO  c.b.e.ElasticLogIndexerThreadownerImpl - onFailure exception - numreqs= 3  after 30177
java.net.SocketTimeoutException: null
        at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.timeout(HttpAsyncRequestExecutor.java:375)
        at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:92)
        at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:39)
        at org.apache.http.impl.nio.reactor.AbstractIODispatch.timeout(AbstractIODispatch.java:175)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionTimedOut(BaseIOReactor.java:263)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.timeoutCheck(AbstractIOReactor.java:492)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:213)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
        at java.lang.Thread.run(Thread.java:748)

**Comment by kdotson3263k** [comment]
I am also seeing the following on some of my bwlogreceiver servers:

2019-09-17_19:33:09.550 [LogProcessor #1] INFO  c.b.e.I.ApacheChannelIndexBuilder - Referrer " not found
2019-09-17_19:33:09.550 [LogProcessor #2] INFO  c.b.e.I.ApacheChannelIndexBuilder - Referrer " not found
2019-09-17_19:33:09.550 [LogProcessor #5] INFO  c.b.e.I.ApacheChannelIndexBuilder - Referrer " not found
2019-09-17_19:33:09.550 [LogProcessor #7] INFO  c.b.e.I.ApacheChannelIndexBuilder - Referrer " not found
2019-09-17_19:33:09.550 [LogProcessor #0] INFO  c.b.e.I.ApacheChannelIndexBuilder - Referrer " not found
2019-09-17_19:33:09.550 [LogProcessor #4] INFO  c.b.e.I.ApacheChannelIndexBuilder - Referrer " not found


any help would be appreciated.

**Comment by kdotson3263k** [comment]
FYI I found a configuration error in the logreceiver.props, that caused the 
"2019-09-17_19:33:09.550 [LogProcessor #1] INFO c.b.e.I.ApacheChannelIndexBuilder - Referrer " not found"


I am still looking for some help with java exception.

**Comment by MistAssassin** [comment]
I am also running into the SocketTimeoutException. Not real sure how to proceed from here.

2019-10-28_14:26:01.021 [I/O dispatcher 3] INFO  c.b.e.ElasticLogIndexerThreadownerImpl - onFailure exception - numreqs= 3  after 30402
java.net.SocketTimeoutException: null
        at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.timeout(HttpAsyncRequestExecutor.java:375)
        at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:92)
        at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:39)
        at org.apache.http.impl.nio.reactor.AbstractIODispatch.timeout(AbstractIODispatch.java:175)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionTimedOut(BaseIOReactor.java:263)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.timeoutCheck(AbstractIOReactor.java:492)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:213)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by sdetwiler85** [comment]
We have this problem as well. It really makes the whole build unusable as we see it happen about every hour, for 15mins, and we lose the data for those 15min.
