### ISSUE TITLE
[bwcdrprrocessor] no index creation

### ISSUE THREAD

**Issue by Xitras** [BroadSoft-Xtended/BroadWorks-Dashboards-and-Discovery#92]
Hi,

We have the bwcdrprocessor on a separate machine that connects to elasticsearch without problems but can't make it work...  this is the log output "bwcdrprocessor.log.txt"

`2019-12-04_11:36:07.343 [main] INFO  c.b.e.ElasticImporter - starting up.
2019-12-04_11:36:07.347 [main] INFO  c.b.elasticcdrimporter.AppProperties - Property STARTPATH resolved to </home/ikusi/bwcdrprocessor/bwcdrprocessor_1307>`
`2019-12-04_11:36:07.347 [main] INFO  c.b.elasticcdrimporter.AppProperties - Property USEKAFKA resolved to <NO>`
`2019-12-04_11:36:07.349 [main] INFO  c.b.elasticcdrimporter.AppProperties - Property ELASTICHOST resolved to <10.30.0.109>`
`2019-12-04_11:36:07.350 [main] INFO  c.b.elasticcdrimporter.AppProperties - Property ELASTICPORT resolved to <9200>`
`2019-12-04_11:36:07.350 [main] INFO  c.b.elasticcdrimporter.AppProperties - Property ELASTICPORT resolved to <9200>
2019-12-04_11:36:07.350 [main] INFO  c.b.elasticcdrimporter.AppProperties - Property ELASTICCLUSTER resolved to <cluster>`
`2019-12-04_11:36:07.350 [main] INFO  c.b.elasticcdrimporter.AppProperties - Property ESAUTHUSER resolved to <elastic>
2019-12-04_11:36:07.350 [main] INFO  c.b.elasticcdrimporter.AppProperties - Property ESAUTHPASS resolved to <passwordaqui>
2019-12-04_11:36:07.350 [main] INFO  c.b.elasticcdrimporter.AppProperties - Property TRUSTSTOREPATH resolved to </home/ikusi/acliente-certificate.p12>
2019-12-04_11:36:07.350 [main] INFO  c.b.elasticcdrimporter.AppProperties - Property TRUSTSTOREPASSWORD resolved to <passwordaqui>`
`2019-12-04_11:36:08.044 [main] WARN  c.b.e.ElasticInterface - failure pinging:
javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
        at sun.security.ssl.EngineInputRecord.bytesInCompletePacket(EngineInputRecord.java:156)
        at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:857)
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:766)
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
        at org.apache.http.nio.reactor.ssl.SSLIOSession.doUnwrap(SSLIOSession.java:273)
        at org.apache.http.nio.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:328)
        at org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:509)
        at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:120)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
        at java.lang.Thread.run(Thread.java:748)`
`2019-12-04_11:36:08.048 [main] INFO  c.b.e.ElasticImporter - Processing a single file -> /home/cdrparrot/DONE/new/BW-CDR-20191203231500-2-005056A617B5-090818.xml
2019-12-04_11:36:08.048 [main] INFO  c.b.e.ElasticImporter - Processing => /home/cdrparrot/DONE/new/BW-CDR-20191203231500-2-005056A617B5-090818.xml
2019-12-04_11:36:08.048 [main] INFO  c.b.elasticcdrimporter.XMLLoader - XMLLoader: Process -> /home/cdrparrot/DONE/new/BW-CDR-20191203231500-2-005056A617B5-090818.xml`
`2019-12-04_11:36:08.098 [main] INFO  c.b.elasticcdrimporter.XMLLoader - Bad cdrType ===> Start
2019-12-04_11:36:08.099 [main] INFO  c.b.elasticcdrimporter.XMLLoader - Bad cdrType ===> End
2019-12-04_11:36:08.099 [main] INFO  c.b.e.ElasticInterface - restClient.close
2019-12-04_11:36:08.100 [main] INFO  c.b.e.ElasticImporter - exiting.`

Hope you could give us light on this.  
Apart from that, is there any more information/doc about the "elasticsearchcdr.jar" file?

Thank you.

Rolando.

**Comment by gokulbsft** [comment]
Whether the X-Pack Security is installed on your ElasticSearch?

**Comment by Xitras** [comment]
> Whether the X-Pack Security is installed on your ElasticSearch?

Hi gokulbsf,

At first we try without the Xpack installed and we noticed is "mandatory" the certificate, so we enable security on ES and the process seems to advance ok until the "WARN" part of the lob above. (2019-12-04_11:36:08.044 [main] WARN c.b.e.ElasticInterface ... )

Maybe we miss something but we are not sure what it is because if we miss the certificate password the process stoped, or if the password are incorrect.

Tks for your help.

**Comment by Xitras** [comment]
Hello again, 

Still can't make it work... We are trying to figure out about "Mandatory" security locks the toolkit has, but as the documents did't mention it we are at trail and error. 

Any hint would be apreciated.

Tks.

**Comment by gokulbsft** [comment]
Can you provide the content of elasticsearch.yml file from your setup?

**Comment by Xitras** [comment]
> Can you provide the content of elasticsearch.yml file from your setup?
Sure, this is the content:
----------------
cluster.name: cliente
node.name: COORD01
node.master: true
node.data: false
node.ingest: true
node.ml: false
#network.host: _site_
network.host: ["localhost", "elk05", "elk05-mgmt"]
discovery.seed_hosts: ["elk01","elk02","elk03","elk04","elk05"]
cluster.initial_master_nodes: ["MASTER01","MASTER02","COORD01"]
action.destructive_requires_name: true
script.painless.regex.enabled: true
transport.host: elk05
network.publish_host: elk05
###
path.data: /data/elasticsearch
path.logs: /data/logs
###
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.keystore.path: cliente-certificate.p12
xpack.security.transport.ssl.keystore.password: "password"
xpack.security.transport.ssl.truststore.path: cliente-certificate.p12
xpack.security.transport.ssl.truststore.password: "password"
----------------
I just changed sensitive data.

**Comment by gokulbsft** [comment]
It looks the xpack is not set for http clients. Can you set http security settings (xpack.security.http.ssl.*) as well and check?

**Comment by Xitras** [comment]
Hi gokulbsft,  tks for the reply.

I Already try enabling the security but had the same problem.
Could you provide me with the content of the **elasticsearchcdr.jar** file so we could work it out?

Best Regards.
