### ISSUE TITLE
Not able to start bwlogreceiver while security is enabled in ES 7.3.2

### ISSUE THREAD

**Issue by ansarpalakottal** [BroadSoft-Xtended/BroadWorks-Dashboards-and-Discovery#95]
I have Elasticsearch cluster with version **7.3.2** and security is enabled. I configured bwlogreceiver with elasticsearch host, cluster name, user ID, password, truststore path and truststore password. But I am not able to start bwlogreceiver.

It is giving the below exception
```
2020-01-07_10:29:46.557 [Thread-3] INFO  c.b.e.ElasticLogIndexerThreadownerImpl - starting ES indexer thread
2020-01-07_10:29:46.956 [main] INFO  c.b.e.ElasticLogIndexer - Exception creating the RestClient
javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
        at sun.security.ssl.EngineInputRecord.bytesInCompletePacket(EngineInputRecord.java:156)
        at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:868)
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
        at org.apache.http.nio.reactor.ssl.SSLIOSession.doUnwrap(SSLIOSession.java:273)
        at org.apache.http.nio.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:328)
        at org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:509)
        at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:120)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
        at java.lang.Thread.run(Thread.java:748)
2020-01-07_10:29:46.958 [Thread-2] INFO  c.b.eslogzipreceiver.ShutdownHandler - Caught shutdown.... Exiting nicely (Well, not yet - but to be implemented)
```

I can start bwlogreceiver when security is disabled in elasticsearch 7.3.2 cluster.

**Comment by ansarpalakottal** [comment]
I tried with elasticsearch version 7.1.1 and I am facing the same issue. I am unable to start bwlogreceiver. and throwing the above same exception.

Can anyone help me ?

**Comment by gokulbsft** [comment]
This error sounds more like the security pack is not properly enabled in Elastic Server. That is, the bwlogreceiver application tries to make "https" request that is not supported by your Elastic Server. Anyway, I am analyzing more on this. Meanwhile, can you confirm that ES is set up properly with security configurations?

**Comment by ansarpalakottal** [comment]
@gokulbsft I have enabled security, https with another cluster and are able to push data to that cluster. Is there anyway to index data to the elasticsearch cluster without enabling SSL and with security.

That is,

I need to push the data to an ES cluster having username and password and without SSL(https).
